export const SET_USER_INFO = "SET_USER_INFO";
export const SET_IS_LOGGEDIN = "SET_IS_LOGGEDIN";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SHOW_TOAST = "SET_SHOW_TOAST";
